### PR TITLE
Merge Dev to Main 08/25/2023

### PR DESCRIPTION
**Pull request by emersoncloud**
* Update frontend copy to remove the word "borrow" 
* New trackers for project management 
* All input forms updated to handle BigNumbers natively! 
* Dashboard UI to show why a minipool errored 
* API endpoint for APY estimates
* Fix ClaimAndRestake for good
* Removed Storybook

### CODE REVIEW

**Comment by emersoncloud** [comment]
Don't squash and merge

**Comment by Namaskar-1F64F** [comment]
lots of good stuff in here. nice work team 👍

**Review by jacktrusler — APPROVED** [review]
Big Number changes are gonna be nice. :>

**Comment by jacktrusler** [comment]
Added one more small styling change: 

- Coming soon page removed as it was causing confusion, now nav bar just contains an unclickable NavItem.

**Pull request merged**
