### PR TITLE
Dev to Main Merge

### PR DESCRIPTION
**Pull request by emersoncloud**
Here's what we added in this edition of dev to main

1. Network context, in the form of `useWeb3` we can access common variables across the entire app. 
2. Switch to unified endpoints at `api.gogopool.com`. Just have one api where we can get all data we need for the FE
3. More information on rewards eligibility status
4. Umami analytics 
4. GGP one click rework to allow for custom amounts of GGP purchase depending on the users collateralization

### CODE REVIEW

**Comment by WillDosSantos** [comment]
Testing on beta and noticed a few things. 

1. Gray Border needs to be removed from the NEW pill
2. Node Hardware cost keeps spinning for a long while - not giving me a price
3. Select dropdowns have a gray background - needs to be removed so the background is white or transparent


Screenshot 2024-02-15 at 1 49 02 PM
src="https://github.com/multisig-labs/app.gogopool.com/assets/1126074/24b9bd00-fa41-4c45-a736-5a83bbfb725c">

**Comment by WillDosSantos** [comment]
Oonodz logo is too big - reference comp for correct size
https://www.figma.com/file/UMPEc0eW9iZyx5UlBXpCdi/Product-Design---GoGoPool?type=design&node-id=6999%3A8745&mode=design&t=lCU9HWu7zo156HUC-1

Screenshot 2024-02-15 at 1 52 53 PM

**Comment by WillDosSantos** [comment]
Paragraph and alert font size should be the same. I would default to the paragraph size in this case

Screenshot 2024-02-15 at 1 58 29 PM

**Review by chand1012 — APPROVED** [review]
LGTM on behalf of @emersoncloud

**Pull request merged**
