### PR TITLE
Finished rewards

### PR DESCRIPTION
**Pull request by jacktrusler**
Made it so when all minipools have errored / been cancelled / or finished, the rewards card will display "All of your minipools have finished"

### CODE REVIEW

**Review by emersoncloud — APPROVED** [review]
This looks good to me, but make sure the branch is going to merge alright. Do you know what caused all that merge business?

**Comment by emersoncloud** [comment]
image

**Comment by jacktrusler** [comment]
> image

I think this is just from me, merging periodically from dev.

**Comment by jacktrusler** [comment]
> This looks good to me, but make sure the branch is going to merge alright. Do you know what caused all that merge business?

I think this is just from merging periodically from dev

**Pull request merged**
